def rules():
    return("**📖 Comandos disponíveis:**\n\n"
        "Ajuda:\n"
        "`rp!help` → Exibe esta mensagem\n"
        "\nRolar dados:\n"
        "`rp!d2` → Rola um dado de 2 lados\n"
        "`rp!d4` → Rola um dado de 4 lados\n"
        "`rp!d6` → Rola um dado de 6 lados\n"
        "`rp!d10` → Rola um dado de 10 lados\n"
        "`rp!d20` → Rola um dado de 20 lados\n"
        "`rp!d100` → Rola um dado de 100 lados\n"
        "\nSistema de Batalha:\n"
        "`rp!battle @player1 hp1 @player2 hp2` → Inicia uma batalha 1x1 automática entre dois jogadores\n"
        "  - hp1 e hp2 devem estar entre 1 e 100\n"
        "  - Batalha roda automaticamente com turnos de 3 segundos\n"
        "`rp!forfeit` → Desiste da batalha atual\n"
        "`rp!resume` → Retoma uma batalha que foi parada\n"
        "`rp!log` → Mostra o log simplificado da batalha atual\n"
        "\nComandos de Administração:\n"
        "`rp!debug` → Mostra informações de debug sobre batalhas ativas\n"
        "`rp!clear` → Limpa batalha travada no canal atual\n"
        "\nMecânica da Batalha Automática:\n"
        "⚔️ **Sistema Automático** → Ataques e defesas rodam automaticamente\n"
        "⏱️ **Timer** → 3 segundos entre cada turno\n"
        "🔄 **Contínua** → Batalha continua até um jogador chegar a HP 0\n"
        "\nTabela de Dano (Ataque):\n"
        "0 → Causa 1 de dano a si mesmo\n"
        "1-4 → Causa 1-4 de dano\n"
        "5-10 → Causa 5-10 de dano\n"
        "11-15 → Causa 11-15 de dano\n"
        "16-19 → Causa 16-19 de dano\n"
        "20 → Causa 25 de dano crítico\n"
        "21 → Causa 20 de dano crítico e recupera 5 HP\n"
        "\nTabela de Defesa:\n"
        "0-4 → Não defende\n"
        "5 → Defesa quase inútil (1 de redução)\n"
        "6-9 → Defesa parcial (valor rolado - 2)\n"
        "10-17 → Defesa quase perfeita (10 de redução)\n"
        "18-19 → Esquiva 100% do dano\n"
        "20 → Esquiva 100% e retorna 5 de dano (parry)\n"
        "21 → Esquiva 100% e recupera 5 HP")
